# Generated by Django 4.0.4 on 2022-06-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='social_github',
            new_name='social_facebook',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='social_linkedin',
            new_name='social_instagram',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='social_website',
            new_name='social_pinterest',
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
