# Generated by Django 4.0.4 on 2022-06-06 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0002_rename_name_profile_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='website',
            new_name='social_website',
        ),
    ]
