# Generated by Django 4.0.4 on 2022-06-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0005_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
