# Generated by Django 4.0.4 on 2022-06-13 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0008_rename_full_name_profile_name'),
        ('blog', '0009_post_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='writers.profile'),
        ),
    ]
